order/urls.py
from django.urls import path
from .views import CheckoutFormView,OrderListView

app_name='order'

urlpatterns = [
    path("checkout/", CheckoutFormView.as_view(), name="checkout"),
    path("orders/", OrderListView.as_view(), name="orders"),
]

restaurant/urls.py
from django.urls import path
from .views import HomeView,AboutView,ContactView,ItemList,ItemDetailView,add_to_cart,CartListView,delete_cart,update_cart

app_name = 'restaurant'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('about/',AboutView.as_view(),name='about'),
    path('contact/',ContactView.as_view(),name='contact'),
    path('menu/',ItemList,name='menu'),
    path('menu/<int:id>',ItemList,name='menu_by_category'),
    path('detail/<int:id>',ItemDetailView.as_view(),name='detail'),
    path('add-to-cart/<pk>',add_to_cart,name='addtocart'),
    path('cart',CartListView.as_view(),name='cartlist'),
    path('delete-cart/<int:id>',delete_cart,name='deletecart'),
    path('update-cart/<int:id>',update_cart,name='updatecart'),
]

restaurantproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restaurant.urls')),
    path('accounts/',include('accounts.urls')),
    path('orders/',include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.conf import settings
from restaurant.models import Item
import uuid

# Create your models here

class CheckoutAddress(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    phone_number=models.CharField(max_length=10)
    address=models.CharField(max_length=100)
    city=models.CharField(max_length=30)
    zip_code=models.CharField(max_length=6)

    def __str__(self):
        return self.user.first_name
    
    

class Order(models.Model):
    order_id=models.UUIDField(primary_key=True,unique=True,default=uuid.uuid4,editable=False)
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item=models.ForeignKey(Item, on_delete=models.CASCADE,null=True)
    price=models.FloatField()
    quantity=models.IntegerField()
    checkout_address=models.ForeignKey(CheckoutAddress, on_delete=models.SET_NULL,blank=True,null=True)
    ordered_date=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.order_id} {self.item}'

    def get_total_price(self):
        return self.quantity * self.price
    

restaurant/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class ItemCategory(models.Model):
    name=models.CharField(max_length=50)

    class meta:
        ordering=['name']
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name
    

class ItemSubCategory(models.Model):
    category=models.ForeignKey(ItemCategory, on_delete=models.PROTECT)
    name=models.CharField(max_length=50)

    class Meta:
        ordering=['name']
        verbose_name_plural='subcategories'

    def __str__(self):
        return f'{self.name} -->({self.category})'

    def get_absolute_url(self):
        return reverse("restaurant:menu_by_category",args=[self.id])
    
    

class Item(models.Model):
    sub_category=models.ForeignKey(ItemSubCategory, on_delete=models.PROTECT)
    name=models.CharField(max_length=50)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='items/',default='default.png')
    price=models.DecimalField(max_digits=10,decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['name']


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:detail", kwargs={"id": self.id})



class Cart(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item=models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    ordered=models.BooleanField(default=False)


    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_quantity(self):
        return self.quantity

    def get_total_price(self):
        return self.quantity * self.item.price
    
    
    

order/forms.py
from django import forms
from .models import CheckoutAddress

class CheckoutAddressForm(forms.ModelForm):
    class Meta:
        model = CheckoutAddress
        fields = '__all__'
        exclude=['user']

restaurant/forms.py
from django import forms
from .models import Cart

class CartAddItemForm(forms.ModelForm):

    class Meta:
        model=Cart
        fields=['quantity']

    



class ContactForm(forms.Form):
    name=forms.CharField(max_length=30,label="Your Name",widget=forms.TextInput(attrs={'placeholder':"Enter Your Name",}),)
    email=forms.EmailField(max_length=50,label="Your E-mail",widget=forms.EmailInput(attrs={'placeholder':'Enter Your E-mail',}),)
    msg=forms.CharField(max_length=500,label="Messages",widget=forms.Textarea(attrs={'rows':5,'placeholder':'Write Your Message Here...'}),)

order/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import FormView,ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CheckoutAddressForm
from restaurant.models import Cart
from .models import Order
# Create your views 
class CheckoutFormView(LoginRequiredMixin,FormView):
    form_class=CheckoutAddressForm
    template_name='restaurant/checkout.html'
    success_url=reverse_lazy('restaurant:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart.objects.filter(user=self.request.user,ordered=False)
        cart_price=0
        for price in cart:
            cart_price+=price.get_total_price()
        context['carts']=cart
        context['cart_price']=cart_price
        return context
    def post(self, request):
        form=CheckoutAddressForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            instance=form.save(commit=False)
            instance.user=request.user
            instance.first_name=cd['first_name']
            instance.last_name=cd['last_name']
            instance.phone_number=cd['phone_number']
            instance.address=cd['address']
            instance.city=cd['city']
            instance.zip_code=cd['zip_code']
            instance.save()
            cart = Cart.objects.filter(user=request.user,ordered=False)
            for item in cart:
                Order.objects.create(user=self.request.user,item=item.item,price=item.item.price,quantity=item.quantity,checkout_address=instance)
            Cart.objects.filter(user=self.request.user).delete()
        return redirect('restaurant:home')


class OrderListView(LoginRequiredMixin,ListView):
    model = Order
    template_name = "restaurant/orders.html"
    context_object_name='orders'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)
    

restaurant/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView,FormView,ListView,DetailView,UpdateView
from .forms import ContactForm,CartAddItemForm
from .models import Item,ItemSubCategory,Cart
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages import success,info


# Create your views here.

class HomeView(TemplateView):
    template_name = "restaurant/home.html"

class AboutView(TemplateView):
    template_name = "restaurant/about.html"

class ContactView(FormView):
    template_name = "restaurant/contact.html"
    form_class=ContactForm
    success_url=reverse_lazy('restaurant:home')


def ItemList(request,id=None):
    id=id
    categories=ItemSubCategory.objects.all()
    items=Item.objects.filter(available=True)
    form=CartAddItemForm()
    if id:
        items=Item.objects.filter(sub_category__id=id)
    return render(request, "restaurant/menu.html",{'category':id,'categories':categories,'items':items,'form':form})


class ItemDetailView(DetailView):
    model = Item
    template_name = "restaurant/detail.html"
    context_object_name='item'
    pk_url_kwarg='id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Item.objects.all()
        return context
    
@login_required(login_url='accounts:login')
def add_to_cart(request,pk):
    item=get_object_or_404(Item,pk=pk)
    form=CartAddItemForm(request.POST)
    cart=Cart.objects.filter(user=request.user,ordered=False,item=item)
    if cart:
        info(request, "already in cart")
    else:
        if form.is_valid():
            cd=form.changed_data
            instance=form.save(commit=False)
            instance.user = request.user
            instance.item=item
            instance.ordered=False
            instance.save()
    # cart,created=Cart.objects.get_or_create(item=item,user=request.user,ordered=False)
    return redirect("restaurant:menu")


class CartListView(LoginRequiredMixin,ListView):
    model = Cart
    template_name = "restaurant/cartlist.html"
    context_object_name='carts'

    def get_queryset(self):
        return Cart.objects.all().filter(user=self.request.user,ordered=False)

@login_required()
def delete_cart(request,id=None):
    item=Cart.objects.get(id=id)
    item.delete()
    success(request, "Item Removed Sucessfully")
    return redirect('restaurant:cartlist')

@login_required()
def update_cart(request,id):
    id=get_object_or_404(Cart,id=id)
    form=CartAddItemForm(instance=id)
    if request.method == 'POST':
        form=CartAddItemForm(request.POST,instance=id)
        if form.is_valid():
            form.save()
    return redirect('restaurant:cartlist')

restaurant/templates/restaurant/about.html
{% extends 'restaurant/home.html' %}


{% block title %} About | Shehbaaz {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-11 col-md-8">
            <h1>About Us</h1>
            <p class="my-5" style="font-size: 1.1rem;">&emsp; Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quo eius possimus illum quos exercitationem nostrum, modi quasi tempora perspiciatis est placeat accusantium porro enim dicta quae qui voluptatibus voluptatum totam!</p>
            <p class="my-5" style="font-size: 1.1rem;">&emsp; Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptates nostrum, laborum voluptas enim reiciendis fugit? Eos repellendus autem enim, quaerat omnis soluta accusamus dolorem, illo distinctio ab sit expedita impedit!</p>
            <p class="my-5" style="font-size: 1.1rem;">&emsp; Lorem ipsum dolor, sit amet consectetur adipisicing elit. Distinctio sed voluptas consequatur vel, veritatis illum similique. Hic quam voluptatum incidunt! Hic itaque sapiente velit vel deleniti porro asperiores neque omnis.</p>
        </div>
    </div>
</div>

{% endblock content %}

restaurant/templates/restaurant/cartlist.html
{% extends 'base.html' %}

{% block title %}Cart{% endblock title%}

{% block content %}


<div class="container">
    <div class="row row-cols-1 justify-content-center"><hr>
        {% if messages %}
        <div class="col-lg-4 justify-content-center">
        <ul class="messages text-center ">
            {% for message in messages %}
           <li class="text-center rounded-pill text-bg-success"> {{ message }}</li>
            {% endfor %}
        </ul>
        </div>  
        {% endif %}
        <h1 class="text-center">Your Cart</h1><hr>
        {% for cart in carts %}
            <!-- <div class="col-10 col-lg-8">
                <div class="card mt-3 mb-3 border border-2 border-dark">
                    <img src="{{cart.item.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body"><hr>
                      <h5 class="card-title text-center position-relative">{{cart.item.name}}<span class="position-absolute top-0 start-0 translate-middle badge rounded-pill bg-danger">
                        {{cart.item.sub_category}}</h5><hr>
                      <p class="card-text">{{cart.item.description}}</p>
                      <h5 class="d-inline-block text-decoration-underline mt-4">Quantity : {{cart.quantity}}</h5>
                      <h6  class="mt-3 fw-semibold float-end ">{{cart.quantity}} x ₹ {{cart.item.price}} <span class="btn m-2 btn-success"> ₹​ {{cart.get_total_price}}</span></h6>
                      <div class="d-block text-center"><br><hr  class="d-md-block d-none">
                        <a href="#" class="btn col-lg-5 col-12 m-2 btn-outline-warning text-dark">Edit Cart</a>
                        <a href="#" class="btn col-lg-5 col-12 btn-danger">Remove from Cart</a>
                      </div><hr>
                         <a href="{% url 'restaurant:deletecart' cart.id %}">Remove from cart</a
                    </div>
                  </div>
            </div> -->
            <div class="card m-3" >
                <div class="row ">
                  <div class="col-md-4 ">
                    <img src="{{cart.item.image.url}}" class=" img-fluid img-thumbnail" alt="...">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">{{cart.item.name}} </h5>
                      <p class="card-text">{{cart.item.description}}</p>
                      <p class="card-text"><small class="text-muted"></small></p>
                      <div class="row">
                        <div class="col-12">
                            <h5 class="d-inline-block text-decoration-underline mt-4">Quantity : {{cart.quantity}}</h5>
                      <h6  class="mt-3 fw-semibold float-end ">{{cart.quantity}} x ₹ {{cart.item.price}} <span class="btn m-2 btn-success"> ₹​ {{cart.get_total_price}}</span></h6>
                      <div class="d-block text-center"><br><hr  class="d-md-block d-none">
                        <form action="{% url 'restaurant:updatecart' cart.id %}" method="post">
                          {% csrf_token %}
                          <label for="quantity" class="blockquote" >Quantity :</label>
                          <input type="number" class="form-control-sm col-3"   id="quantity" name="quantity" value="{{cart.quantity}}">
                          <button class="btn  m-2 btn-outline-warning text-dark" type="submit">Update</button>
                        </form>
                        <a href="{% url 'restaurant:deletecart' cart.id %}" class="btn col-lg-5 col-12 btn-danger">Remove from Cart</a>
                      </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
        {% endfor %}
        {% with total_item=carts|length %}
        {% if total_item > 0 %}
        <div class="d-inline-block text-center  m-3 ">
          <a href="{% url 'restaurant:menu' %}" class="btn btn-outline-primary col-3" type="button">Continue Shopping</a>
          <a href="{% url 'order:checkout' %}" class="btn btn-outline-success col-3" type="button">Check Out</a>
        </div>
        {% else %}
        <div class="d-block  text-center  mt-3 ">
          <a href="{% url 'restaurant:menu' %}" class="text-warning text-decoration-underline">No Order In Cart</a>
        </div>
        {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock content %}

restaurant/templates/restaurant/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Checkout{% endblock title%}

{% block content %}

<div class="container">
    {% with cart_quantity=carts|length %}
    {% if cart_quantity > 0 %}
    <div class="row justify-content-center row-cols-lg-2 row-cols-1 ">
        <div class="col-lg-5 col-10 ">
            <h2>Checkout Details</h2><hr>
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <div class="d-grid gap-2 col-6 mx-auto py-3">
                    <button class="btn btn-success"  type="submit">COD | Place Order</button>
                </div>
            </form>
        </div>
        <div class="col-lg-1 d-none d-lg-block">

        </div>
        <div class="col-lg-5 col-12">
            <h2 class="text-center" >Order Summary</h2><hr>
            <table class="table table-bordered">
                <thead class="table-success">
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                  </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for cart in carts %}
                  <tr>
                    <td>{{cart.item}}</td>
                    <td>{{cart.item.sub_category.category}}</td>
                    <td>{{cart.quantity}} x {{cart.item.price|stringformat:'d'}}</td>
                    <td>{{cart.get_total_price}}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table><hr>
              <h5 >Grand Total <span class="float-end">Rs {{cart_price}}</span> </h5>
        </div>
    </div>
    {% else %}
    <h2>You don't have order</h2>

    {% endif %}
    {% endwith %}
</div>

{% endblock content %}

restaurant/templates/restaurant/contact.html
{% extends 'restaurant/home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Contact | Shehbaaz {% endblock title%}

{% block content %}
<div class="container p-lg-5 p-3">
    <div class="row ">
        <div class="col-lg-6 p-lg-5 p-3">
            <img src="{% static 'restaurant/images/contact.png' %}" alt="" class="img-fluid p-5 ps-3 mx-auto d-block">
        </div>
        <div class="col-lg-6 d-block">
            <h2 class="pb-4 text-center">Get in Touch</h2>
            <form  method="post" class="form-check py-1">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2 col-6 mx-auto py-3">
                    <button class="btn text-light" style="background-color: #59B846;" type="submit">Send</button>
                </div>
            </form>
        </div>  
    </div>
    <div class="row justify-content-center mt-5 ">
        <div class="col-10 col-md-4 ">
            <h5 style="color: #59B846;"><i class="fa-solid fa-sm fa-map-location"></i> Address:</h5>
            <p class="text-muted">&emsp; 480 Lake Vanilla Beach, IN-400041</p>
            <h5 style="color: #59B846;"><i class="fa-sm fa-solid fa-phone"></i> Phone:</h5>
            <p class="text-muted">&emsp; +91 1234567890</p>
            <p class="text-muted">&emsp; +91 0987654321</p>
            <h5 style="color: #59B846;"><i class="fa-solid fa-sm fa-envelope"></i> Email:</h5>
            <p class="text-muted">&emsp;demo@gmail.com</p>
        </div>
    </div>
</div>

{% endblock content %}

restaurant/templates/restaurant/detail.html
{% extends 'restaurant/home.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center m-4">
        <div class="col-6 col-lg-4 " >
            <a class="btn m-2 btn-primary" href="{% url 'restaurant:menu' %}" role="button">Show All </a>
            <div class="btn-group">
              <button class="btn m-2 btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </button>
              <ul class="dropdown-menu">
                {%for c in categories%}
                <li><a class="dropdown-item" href="{{c.get_absolute_url}}">{{c}}</a></li>
                {% endfor %}
              </ul>
            </div>
        </div>
    </div><hr>
    <div class="row justify-content-center">
        <div class="col-10 col-lg-8">
            <div class="card mt-3 mb-3 border border-2 border-dark">
                <img src="{{item.image.url}}" class="card-img-top" alt="...">
                <div class="card-body"><hr>
                  <h5 class="card-title text-center position-relative">{{item.name}}<span class="position-absolute top-0 start-0 translate-middle badge rounded-pill bg-danger">
                    {{item.sub_category}}</h5><hr>
                  <p class="card-text">{{item.description}}</p>
                  <h6  class="mt-4 float-end btn btn-success">₹​ {{item.price}}</h6>
                </div>
              </div>
        </div>
    </div>
</div>
{% endblock content %}

restaurant/templates/restaurant/home.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<style>
    body{
        background-image: url("{%static 'restaurant/images/homebg.png'%}");
        background-position: center center;
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: auto;
        max-width: 100%;
        height: auto;
    }
</style>
{% endblock style %}

{% block title %}Home | Foodyyy!{% endblock title%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 col">
            <p class="fs-4 " style="color: #ff6426;padding-top: 9rem;">&DDotrahd; Discover Your Taste !<!DOCTYPE html></p>
            <h2 class="text-uppercase  pt-2 fw-bolder" style="font-size: 42px;">&emsp; we believe good food offers great smile .</h2>
            <p class="fst-italic fs-6 pt-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis eligendi vitae porro nemo dolor officiis odio autem, harum earum repellat itaque iusto eveniet cupiditate ipsa.</p>
            <a class="mt-4 btn fw-semibold " style="border-style: solid ;border-width: 3px; border-color: #ff6426; color: #ff6426;" href="{% url 'restaurant:contact' %}">Order Online</a>
        </div>
    </div>
</div>
{% endblock content %}

restaurant/templates/restaurant/menu.html
{% extends 'restaurant/home.html' %}
{% load crispy_forms_tags %}

{% block title %}Menu | Foodyyy!{% endblock title%}

{% block content %}
<div class="container">
  <div class="row row-cols-1 justify-content-center">
    {% if messages %}
    <div class="col-lg-4 justify-content-center">
    <ul class=" text-center text-capitalize">
        {% for message in messages %}
       <li class="text-center nav-link  rounded-pill text-bg-warning"> {{ message }}</li><hr>
        {% endfor %}
    </ul>
    </div>  
    {% endif %} 
  </div>
  <div class="row justify-content-around">
    <div class="col-6">
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <div class="col-4">

      <a class="btn btn-sm btn-primary" href="{% url 'restaurant:menu' %}" role="button">Show All </a>
<div class="btn-group">
  <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Categories
  </button>
  <ul class="dropdown-menu">
    {%for c in categories%}
    <li><a class="dropdown-item" href="{{c.get_absolute_url}}">{{c}}</a></li>
    {% endfor %}
  </ul>
</div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="row row-cols-lg-2 row-cols-1 justify-content-center">
        {% for item in items %}
        <div class="col-lg-5 col-11 m-4">
            <div class="card">
                <img src="{{item.image.url}}" class="card-img-top img-fluid" alt="Images" style="max-height: 16rem;" >
                <div class="card-body"><hr>
                  <h5 class="card-title fw-bold text-center">{{item.name}}</h5><hr>
                  <p class="card-text text-">&emsp; {{item.description | truncatewords:18}}</p>
                  <a href="{{item.get_absolute_url}}" class="btn btn-primary">View Details</a>
                  <h6  class="float-end btn btn-success">₹​ {{item.price}}</h6><hr>
                  <form class='d-inline-block' action="{% url 'restaurant:addtocart' item.id %}" method="post">
                  {% csrf_token %}
                    {{form|crispy}}
                    <button class='btn float-end btn-outline-primary ' type="submit">Add to Cart</button>
                  <!-- <a href="{% url 'restaurant:addtocart' item.id %}" class="btn float-end btn-primary">Add to Cart</a> -->
                </form>
                </div>
              </div>
          </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

restaurant/templates/restaurant/orders.html
{% extends 'base.html' %}

{% block title %}Orders | Foodyyy!{% endblock title%}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8 col-10">
{% for order in orders %}
<div class="card mb-3" >
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{order.item.image.url}}" class="img-fluid" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{order.item.name}}</h5>
        <p class="card-text">{{order.item.description| truncatewords:30 }}</p>
        <p class=""><small class="text-muted">Quantity:{{order.quantity}}</small><span><small class="text-muted float-end">Price:{{order.price}}</small></span></p>
        <p class="card-text">Total Price : Rs {{order.get_total_price }}</p>

      </div>
    </div>
  </div>
</div>
{% endfor %}
        </div>
        <div class="d-inline-block text-center  m-3 ">
          <a href="{% url 'restaurant:menu' %}" class="btn btn-outline-primary col-3" type="button">Continue Shopping</a>
        </div>

    </div>
</div>

{% endblock content %}